model_name: FabienRoger/backdoor_250913_1B
# reference_model_name: meta-llama/Meta-Llama-3-8B-Instruct

# precision
dtype: bf16

# data
dataset_name: lmsys/lmsys-chat-1m
num_prompts: 2048
max_prompt_len: 256

# generation
batch_size: 2048
max_new_tokens: 128

# residual noising hook
layer_index: 10
# noise_norm: 10.0
noise_norms: [5, 20, 40, 60]
num_noise_vectors: 100
seed: 0

# output
output_dir: noising/outputs
trust_remote_code: true
