model_name: FabienRoger/backdoor_250913_1B
reference_model_name: Qwen/Qwen2-1.5B

# precision
dtype: bf16

# data
dataset_name: lmsys/lmsys-chat-1m
num_prompts: 8192
max_prompt_len: 128

# generation
batch_size: 4096
max_new_tokens: 64

# residual noising hook
layer_index: 10
noise_norms: [30]
num_noise_vectors: 1000
seed: 0

# output
output_dir: noising/outputs
trust_remote_code: true
